# Custom Language File for Launcher Customizer

[ejs.app]
title = "PokeSquad Launcher"

[ejs.landing]
mediaGitHubURL = "https://docs.terrymarquis.fr/"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://docs.terrymarquis.fr/"

[ejs.settings]
sourceGithubLink = "https://github.com/Nefers12/pokesquadLauncher/"
supportLink = "https://github.com/Nefers12/pokesquadLauncher/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR POKESQUAD"
welcomeDescription = "Allez viens jouer et fait pas chier"
welcomeDescCTA = "ApprÃªtez-vous Ã  sauter dans le bocal !ðŸ¥’"
